name: Docs

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
        working-directory: ./docs
      - run: npx vitepress build
        working-directory: ./docs
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/.vitepress/dist
      - id: deployment
        uses: actions/deploy-pages@v2
